version: '3.8'

services:
  
  postgres:
      image: postgres:latest
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres 
        POSTGRES_DB: asky
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
        - ./init-db:/docker-entrypoint-initdb.d
 
  pyxis:
    build: ./pyxis
    ports:
      - "8001:8001"
    environment:
      DATABASE_URL: "postgresql+asyncpg://postgres:postgres@postgres/asky"
  
  request_management:
    build: ./request_management
    ports:
      - "8002:8002"
  
  gateway:
    build: ./gateway
    ports:
      - "8000:80"

volumes:
  postgres_data: