version: '3'

services:
  
  postgres:
      image: postgres:latest
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres 
        POSTGRES_DB: asky
      ports:
        - "5432:5432"
      volumes:
        - ./init-db:/docker-entrypoint-initdb.d
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 5
 
  pyxis:
    build: ./pyxis
    ports:
      - "8001:8001"
    environment:
      DATABASE_URL: "postgresql+asyncpg://postgres:postgres@postgres/asky"
    depends_on:
      postgres:
        condition: service_healthy

  auth:
    build: ./auth
    ports:
      - "8003:8003"
    environment:
      DATABASE_URL: "postgresql+asyncpg://postgres:postgres@postgres/asky"
    depends_on:
      postgres:
        condition: service_healthy
  
  request_management:
    build: ./request_management
    ports:
      - "8002:8002"
    environment:
      DATABASE_URL: "postgresql+asyncpg://postgres:postgres@postgres/asky"
    depends_on:
      postgres:
        condition: service_healthy
  
  gateway:
    build: ./gateway
    ports:
      - "8000:80"
    depends_on: 
      - pyxis
      - request_management
      - postgres
      - auth
      
volumes:
  postgres_data: