apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: asky
data:
  nginx.conf: |
    worker_processes 1;

    events {
        worker_connections 1024;
    }

    http {
        sendfile on;

        upstream pyxis {
            server pyxis.asky.svc.cluster.local:8001;
        }

        upstream request_management {
            server request-management.asky.svc.cluster.local:8002;
        }

        upstream auth {
            server auth.asky.svc.cluster.local:8003;
        }

        server {
            listen 80;

            location /pyxis {
                proxy_pass http://pyxis;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }

            location /requests {
                proxy_pass http://request_management;
            }

            location /auth {
                proxy_pass http://auth;
            }
        }
    }
