# The name of the shipper that publishes the network data. It can be used to group
# all the transactions sent by a single shipper in the web interface.
# If this option is not defined, the hostname is used.
name: "filebeat"
logging.metrics.enabled: true
xpack.security.enabled: false
xpack.monitoring.enabled: false
setup.ilm.enabled: false
setup.template.enabled: false

monitoring:
  enabled: true
  elasticsearch:
    username: elastic
    password: senha

filebeat.inputs:
- type: container
  paths: 
    - '/var/log/containers/*.log'

filebeat.autodiscover:
  providers:
    - type: kubernetes
      node: ${NODE_NAME}
      hints.enabled: true
      hints.default_config:
        type: container
        paths:
          - /var/log/containers/*.log
          
processors:
- add_docker_metadata:
    host: "unix:///var/run/docker.sock"

output.elasticsearch:
  hosts: "http://0.0.0.0:9200"
  username: "elastic"
  password: "senha"
  indices:
    - index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"
setup.kibana:
  host: "http://kibana:5601"

logging.level: error


http:
  enabled: true
  host: 0.0.0.0

logging.json: true
logging.metrics.enabled: false