name: Publish Docker image

on:
  push:
    branches:
      - main
  release:
    types: [published]
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    strategy:
      matrix:
        service: [request_management, pyxis, auth] 

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v1
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}-${{ matrix.service }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.service }}-

      - name: Create Firebase service account file
        env:
          FIREBASE_SECRET: ${{ secrets.FIREBASE_SECRET }}
        run: |
          echo "${FIREBASE_SECRET}" > ./src/backend/serviceAccountKey.json
          echo "Service account key file created at: $(pwd)/src/backend/serviceAccountKey.json"
          echo "SERVICE_ACCOUNT_KEY_PATH=$(pwd)/src/backend/serviceAccountKey.json" >> $GITHUB_ENV
    

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./src/backend/${{ matrix.service }}
          file: ./src/backend/${{ matrix.service }}/Dockerfile
          push: true
          tags: elisaflemer/asky-${{ matrix.service }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
